# Generated by Django 6.0.5 on 2026-05-19 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('whatsapp_access_token', models.TextField(blank=True, null=True)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_business_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_app_id', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.vendor')),
            ],
        ),
    ]
