# Generated by Django 6.0.5 on 2026-05-19 06:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('whatsapp_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wa_id', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(default='whatsapp', max_length=20)),
                ('platform_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('unread_messages_count', models.IntegerField(default=0)),
                ('last_messaged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='users.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'wa_id')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contact_wa_id', models.CharField(max_length=50)),
                ('wamid', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('is_incoming', models.BooleanField(default=False)),
                ('status', models.CharField(default='sent', max_length=50)),
                ('message_body', models.TextField(blank=True, null=True)),
                ('attachment', models.CharField(blank=True, max_length=500, null=True)),
                ('platform', models.CharField(default='whatsapp', max_length=20)),
                ('platform_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('messaged_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('data', models.JSONField(default=dict)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_service.contact')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='users.vendor')),
            ],
            options={
                'ordering': ['-messaged_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='users.vendor')),
            ],
        ),
    ]
