# Generated by Django 5.2.5 on 2026-06-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_service', '0002_contact_whatsappmessagelog_whatsapptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
