# Generated by Django 5.2.5 on 2026-06-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_service', '0003_whatsapptemplate_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsapptemplate',
            name='updated_at',
        ),
    ]
