# Generated by Django 5.2.5 on 2026-06-20 06:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_globalsetting'),
        ('whatsapp_service', '0004_remove_whatsapptemplate_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_flows', to='users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('start', 'Start Flow'), ('text', 'Text Message'), ('image', 'Image Message'), ('video', 'Video Message'), ('list_message', 'List Message'), ('section', 'List Section'), ('row', 'List Row'), ('button', 'Quick Reply Button')], max_length=50)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='whatsapp_service.chatbotflow')),
            ],
        ),
        migrations.CreateModel(
            name='FlowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='whatsapp_service.chatbotflow')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='whatsapp_service.flownode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='whatsapp_service.flownode')),
            ],
        ),
        migrations.CreateModel(
            name='ListMessageNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=20)),
                ('body_text', models.TextField()),
                ('header_text', models.CharField(blank=True, max_length=60, null=True)),
                ('footer_text', models.CharField(blank=True, max_length=60, null=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='list_data', to='whatsapp_service.flownode')),
            ],
        ),
        migrations.CreateModel(
            name='MediaNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.URLField(max_length=500)),
                ('caption', models.TextField(blank=True, null=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_data', to='whatsapp_service.flownode')),
            ],
        ),
        migrations.CreateModel(
            name='RowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('description', models.CharField(blank=True, max_length=72, null=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='row_data', to='whatsapp_service.flownode')),
                ('section_node', models.ForeignKey(limit_choices_to={'node_type': 'section'}, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='whatsapp_service.flownode')),
            ],
        ),
        migrations.CreateModel(
            name='SectionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('list_message_node', models.ForeignKey(limit_choices_to={'node_type': 'list_message'}, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='whatsapp_service.flownode')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_data', to='whatsapp_service.flownode')),
            ],
        ),
        migrations.CreateModel(
            name='StartTriggerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('trigger_keywords', models.JSONField(blank=True, default=list)),
                ('keyword_matching_type', models.CharField(choices=[('exact', 'Exact keyword match'), ('string', 'String match')], default='exact', max_length=20)),
                ('add_labels', models.JSONField(blank=True, default=list)),
                ('remove_labels', models.JSONField(blank=True, default=list)),
                ('subscribe_sequence_id', models.IntegerField(blank=True, null=True)),
                ('unsubscribe_sequence_id', models.IntegerField(blank=True, null=True)),
                ('assign_to_role', models.CharField(blank=True, max_length=100, null=True)),
                ('save_to_custom_fields', models.JSONField(blank=True, default=list)),
                ('webhook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('sync_to_google_sheets', models.BooleanField(default=False)),
                ('assign_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_triggers', to=settings.AUTH_USER_MODEL)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_data', to='whatsapp_service.flownode')),
            ],
        ),
        migrations.CreateModel(
            name='TextNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_data', to='whatsapp_service.flownode')),
            ],
        ),
    ]
