# Generated by Django 5.2.5 on 2026-06-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_service', '0005_chatbotflow_flownode_flowedge_listmessagenode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flownode',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='sectionnode',
            name='node',
        ),
        migrations.RemoveField(
            model_name='textnode',
            name='node',
        ),
        migrations.RemoveField(
            model_name='medianode',
            name='node',
        ),
        migrations.RemoveField(
            model_name='sectionnode',
            name='list_message_node',
        ),
        migrations.RemoveField(
            model_name='rownode',
            name='section_node',
        ),
        migrations.RemoveField(
            model_name='rownode',
            name='node',
        ),
        migrations.RemoveField(
            model_name='starttriggernode',
            name='node',
        ),
        migrations.RemoveField(
            model_name='listmessagenode',
            name='node',
        ),
        migrations.RemoveField(
            model_name='starttriggernode',
            name='assign_to_user',
        ),
        migrations.AddField(
            model_name='chatbotflow',
            name='flow_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='FlowEdge',
        ),
        migrations.DeleteModel(
            name='TextNode',
        ),
        migrations.DeleteModel(
            name='MediaNode',
        ),
        migrations.DeleteModel(
            name='SectionNode',
        ),
        migrations.DeleteModel(
            name='RowNode',
        ),
        migrations.DeleteModel(
            name='FlowNode',
        ),
        migrations.DeleteModel(
            name='ListMessageNode',
        ),
        migrations.DeleteModel(
            name='StartTriggerNode',
        ),
    ]
