# Generated by Django 6.0.5 on 2026-06-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_globalsetting'),
        ('whatsapp_service', '0006_remove_flownode_flow_remove_sectionnode_node_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_variables', to='users.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('vendor', 'name')},
            },
        ),
    ]
