# Generated by Django 5.0.14 on 2026-07-02 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_service', '0008_sequenceenrollment_sequencedelivery'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sequenceenrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sequenceenrollment',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='sequenceenrollment',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='sequenceenrollment',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='SequenceDelivery',
        ),
        migrations.DeleteModel(
            name='SequenceEnrollment',
        ),
    ]
