# Generated by Django 5.0.14 on 2026-07-02 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_globalsetting'),
        ('whatsapp_service', '0009_alter_sequenceenrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='users.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('message_body', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='whatsapp_service.sequence')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('sequence', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SequenceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('unsubscribed', 'Unsubscribed')], default='active', max_length=20)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_subscriptions', to='whatsapp_service.contact')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_service.sequencestep')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='whatsapp_service.sequence')),
            ],
            options={
                'unique_together': {('contact', 'sequence')},
            },
        ),
    ]
