# Generated by Django 6.0.5 on 2026-07-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_service', '0010_sequence_sequencestep_sequencesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotflow',
            name='label',
            field=models.CharField(blank=True, help_text='Optional audience label for flow targeting.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='label',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
