# Generated by Django 5.0.14 on 2026-07-08 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_globalsetting'),
        ('whatsapp_service', '0011_chatbotflow_label_contact_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_key', models.CharField(max_length=100)),
                ('field_type', models.CharField(default='text', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='users.vendor')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('vendor', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='ContactCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='whatsapp_service.contact')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_values', to='whatsapp_service.customfield')),
            ],
            options={
                'unique_together': {('contact', 'custom_field')},
            },
        ),
    ]
