# Generated by Django 5.0.14 on 2026-07-08 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_globalsetting'),
        ('whatsapp_service', '0012_customfield_contactcustomfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_labels', to='users.vendor')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('vendor', 'name')},
            },
        ),
    ]
