# Generated by Django 5.0.14 on 2026-07-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_globalsetting'),
        ('whatsapp_service', '0013_contactlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='wamid',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappmessagelog',
            unique_together={('vendor', 'wamid')},
        ),
    ]
