# Generated by Django 5.0.14 on 2026-07-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_service', '0014_alter_whatsappmessagelog_wamid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='label',
        ),
        migrations.AddField(
            model_name='contact',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='whatsapp_service.contactlabel'),
        ),
    ]
